"""Scaffold a starter TraceLens eval directory."""

import argparse
import json
import sys
from pathlib import Path

STARTER_TASKS: dict[str, object] = {
    "tasks": [
        {
            "task_id": "starter-capital",
            "name": "Answer a simple geography question",
            "input_data": {
                "question": "What is the capital of France?",
                "answer": "Paris",
            },
            "metadata": {"expected_answer": "Paris"},
            "tags": ["starter"],
        },
        {
            "task_id": "starter-math",
            "name": "Answer a simple arithmetic question",
            "input_data": {
                "question": "What is 2 + 2?",
                "answer": "4",
            },
            "metadata": {"expected_answer": "4"},
            "tags": ["starter"],
        },
    ]
}


ADAPTER_TEMPLATE = '''"""Starter adapter for a TraceLens eval suite.

Replace ``starter_agent`` with a call into your real agent.
"""

from typing import Any

from tracelens import SimpleAdapter


async def starter_agent(input_data: dict[str, Any]) -> dict[str, Any]:
    """Return the canned starter answer from the task input.

    This keeps the generated eval runnable before you wire in a real agent.
    """
    return {"answer": input_data["answer"]}


class StarterAdapter(SimpleAdapter):
    """No-argument adapter loadable by ``tracelens run``."""

    def __init__(self) -> None:
        super().__init__(starter_agent)
'''


GRADER_TEMPLATE = '''"""Starter grader for a TraceLens eval suite."""

from tracelens import CodeGrader, Task, Transcript


class StarterGrader(CodeGrader):
    """Passes when ``final_output["answer"]`` matches task metadata."""

    def __init__(self) -> None:
        super().__init__("starter")

    def compute_metrics(self, transcript: Transcript, task: Task) -> dict[str, float]:
        expected = str(task.metadata["expected_answer"]).strip().lower()
        actual = str(transcript.final_output.get("answer", "")).strip().lower()
        return {"exact_match": float(actual == expected)}

    def determine_pass(
        self,
        metrics: dict[str, float],
        task: Task,
    ) -> tuple[bool, float]:
        score = metrics["exact_match"]
        return score == 1.0, score
'''


README_TEMPLATE = """# TraceLens Starter Eval

This directory was generated by `tracelens init`.

Run the starter suite from the project root:

```bash
tracelens run \\
  --eval-set eval/tasks.json \\
  --adapter eval.adapter.StarterAdapter \\
  --graders eval.grader.StarterGrader \\
  --output eval/results/results.json \\
  --report eval/results/report.md \\
  --save-trials eval/results/trials.json
```

Next steps:

1. Replace `starter_agent` in `eval/adapter.py` with your real agent call.
2. Replace `StarterGrader` in `eval/grader.py` with your real acceptance criteria.
3. Add real task data to `eval/tasks.json`.

Docs: https://ssf0409.github.io/tracelens/getting-started/
"""


WORKFLOW_TEMPLATE = """name: TraceLens Evaluation

on:
  pull_request:
    branches: [main]
    paths:
      - "eval/**"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv venv
          if [ -f pyproject.toml ]; then
            uv sync
          fi
          uv pip install tracelens

      - name: Run TraceLens starter eval
        run: |
          uv run tracelens run \\
            --eval-set eval/tasks.json \\
            --adapter eval.adapter.StarterAdapter \\
            --graders eval.grader.StarterGrader \\
            --output eval/results/results.json \\
            --report eval/results/report.md \\
            --html-report eval/results/report.html \\
            --save-trials eval/results/trials.json

      - name: Add report to job summary
        if: always()
        run: cat eval/results/report.md >> "$GITHUB_STEP_SUMMARY"

      - name: Upload evaluation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tracelens-results
          path: |
            eval/results/results.json
            eval/results/report.md
            eval/results/report.html
            eval/results/trials.json
"""


def add_init_parser(subparsers: argparse._SubParsersAction) -> None:  # type: ignore[type-arg]
    """Add the 'init' subcommand to the CLI."""
    parser = subparsers.add_parser(
        "init",
        help="Scaffold a runnable eval/ directory",
    )
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Project directory to initialize (default: current directory)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite generated files if they already exist",
    )


def _starter_files() -> dict[Path, str]:
    return {
        Path("eval/__init__.py"): '"""Starter TraceLens eval package."""\n',
        Path("eval/tasks.json"): json.dumps(STARTER_TASKS, indent=2) + "\n",
        Path("eval/adapter.py"): ADAPTER_TEMPLATE,
        Path("eval/grader.py"): GRADER_TEMPLATE,
        Path("eval/README.md"): README_TEMPLATE,
        Path(".github/workflows/eval.yml"): WORKFLOW_TEMPLATE,
    }


def cmd_init(args: argparse.Namespace) -> int:
    """Execute the 'init' subcommand."""
    root = Path(args.path)
    files = {root / relative: content for relative, content in _starter_files().items()}

    conflicts = [path for path in files if path.exists()]
    if conflicts and not args.force:
        print("Error: refusing to overwrite existing files:", file=sys.stderr)
        for path in conflicts:
            print(f"  {path}", file=sys.stderr)
        print("Re-run with --force to overwrite generated files.", file=sys.stderr)
        return 1

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    print(f"Initialized TraceLens eval scaffold in {root}")
    return 0
